using UnityEngine;

public class ModelColliderProximityController : MonoBehaviour
{
    public GameObject panelOverlay; // Arrastra el PanelOverlay desde la jerarqu√≠a

    void Start()
    {
        if (panelOverlay != null)
        {
            panelOverlay.SetActive(false); // Asegurar que inicia oculto
        }
        else
        {
            //Debug.LogError("‚ùå PanelOverlay no est√° asignado en el script.");
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        //Debug.Log("üöÄ Algo entr√≥ en el trigger: " + other.gameObject.name);

        if (other.CompareTag("Modelo"))
        {
            //Debug.Log("‚úî Activando PanelOverlay.");
            panelOverlay.SetActive(true);
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Modelo"))
        {
            //Debug.Log("‚ùå Desactivando PanelOverlay.");
            panelOverlay.SetActive(false);
        }
    }
}
